// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: titan/pointer/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgAddERC20NativePointer defines the message structure for the AddERC20NativePointer gRPC service
// method. It allows an account to add a new ERC20 native pointer.
type MsgAddERC20NativePointer struct {
	// The sender address of the message. Should be gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// The token denom of cosmos native token
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// The name of the ERC20 token
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The symbol of the ERC20 token. Should be uppercase
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// The decimals of the ERC20 token. Should be 0-18
	Decimals uint64 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (m *MsgAddERC20NativePointer) Reset()         { *m = MsgAddERC20NativePointer{} }
func (m *MsgAddERC20NativePointer) String() string { return proto.CompactTextString(m) }
func (*MsgAddERC20NativePointer) ProtoMessage()    {}
func (*MsgAddERC20NativePointer) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40ce4f39b4a9357, []int{0}
}
func (m *MsgAddERC20NativePointer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddERC20NativePointer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddERC20NativePointer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddERC20NativePointer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddERC20NativePointer.Merge(m, src)
}
func (m *MsgAddERC20NativePointer) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddERC20NativePointer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddERC20NativePointer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddERC20NativePointer proto.InternalMessageInfo

func (m *MsgAddERC20NativePointer) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAddERC20NativePointer) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MsgAddERC20NativePointer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgAddERC20NativePointer) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MsgAddERC20NativePointer) GetDecimals() uint64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

// MsgAddERC20NativePointerResponse defines the Msg/AddERC20NativePointer response type.
type MsgAddERC20NativePointerResponse struct {
	// The address of the ERC20 contract
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *MsgAddERC20NativePointerResponse) Reset()         { *m = MsgAddERC20NativePointerResponse{} }
func (m *MsgAddERC20NativePointerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddERC20NativePointerResponse) ProtoMessage()    {}
func (*MsgAddERC20NativePointerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40ce4f39b4a9357, []int{1}
}
func (m *MsgAddERC20NativePointerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddERC20NativePointerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddERC20NativePointerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddERC20NativePointerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddERC20NativePointerResponse.Merge(m, src)
}
func (m *MsgAddERC20NativePointerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddERC20NativePointerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddERC20NativePointerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddERC20NativePointerResponse proto.InternalMessageInfo

func (m *MsgAddERC20NativePointerResponse) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAddERC20NativePointer)(nil), "titan.pointer.MsgAddERC20NativePointer")
	proto.RegisterType((*MsgAddERC20NativePointerResponse)(nil), "titan.pointer.MsgAddERC20NativePointerResponse")
}

func init() { proto.RegisterFile("titan/pointer/tx.proto", fileDescriptor_b40ce4f39b4a9357) }

var fileDescriptor_b40ce4f39b4a9357 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x59, 0xf9, 0x13, 0xd9, 0xc4, 0x68, 0x36, 0x48, 0x56, 0x0e, 0x0d, 0xe1, 0x22, 0x1c,
	0x6c, 0x0d, 0x26, 0xde, 0x81, 0x78, 0xc4, 0x98, 0x7a, 0xf3, 0x42, 0x96, 0x76, 0x53, 0x36, 0xd0,
	0xdd, 0xda, 0x1d, 0x4c, 0x79, 0x0b, 0x1f, 0xc5, 0x83, 0x0f, 0xe1, 0x91, 0x78, 0xf2, 0x68, 0xe8,
	0x8b, 0x18, 0x77, 0x8b, 0xc4, 0x44, 0x12, 0x6f, 0xf3, 0xfd, 0xfa, 0xcd, 0xf4, 0xdb, 0x19, 0xdc,
	0x04, 0x01, 0x4c, 0x7a, 0x89, 0x12, 0x12, 0x78, 0xea, 0x41, 0xe6, 0x26, 0xa9, 0x02, 0x45, 0x8e,
	0x0c, 0x77, 0x0b, 0xde, 0x3a, 0x0b, 0x94, 0x8e, 0x95, 0x9e, 0x98, 0x8f, 0x9e, 0x15, 0xd6, 0xd9,
	0x79, 0x41, 0x98, 0x8e, 0x75, 0x34, 0x08, 0xc3, 0x1b, 0x7f, 0xd4, 0xbf, 0xbc, 0x65, 0x20, 0x9e,
	0xf8, 0x9d, 0xed, 0x23, 0xd7, 0xb8, 0xce, 0x96, 0x30, 0x53, 0xa9, 0x80, 0x15, 0x45, 0x6d, 0xd4,
	0xad, 0x0f, 0xe9, 0xfb, 0xeb, 0x45, 0xa3, 0x98, 0x30, 0x08, 0xc3, 0x94, 0x6b, 0x7d, 0x0f, 0xa9,
	0x90, 0x91, 0xbf, 0xb3, 0x92, 0x06, 0xae, 0x82, 0x9a, 0x73, 0x49, 0x0f, 0xbe, 0x7b, 0x7c, 0x2b,
	0x08, 0xc1, 0x15, 0xc9, 0x62, 0x4e, 0xcb, 0x06, 0x9a, 0x9a, 0x34, 0x71, 0x4d, 0xaf, 0xe2, 0xa9,
	0x5a, 0xd0, 0x8a, 0xa1, 0x85, 0x22, 0x2d, 0x7c, 0x18, 0xf2, 0x40, 0xc4, 0x6c, 0xa1, 0x69, 0xb5,
	0x8d, 0xba, 0x15, 0xff, 0x47, 0x77, 0xc6, 0xb8, 0xbd, 0x2f, 0xb1, 0xcf, 0x75, 0xa2, 0xa4, 0xe6,
	0xa4, 0x87, 0x4f, 0x02, 0x25, 0x21, 0x65, 0x01, 0x4c, 0x98, 0x8d, 0x69, 0x1f, 0xe0, 0x1f, 0x6f,
	0x79, 0x91, 0xbe, 0x9f, 0xe1, 0xf2, 0x58, 0x47, 0xe4, 0x11, 0x9f, 0xfe, 0xbd, 0x84, 0x73, 0xf7,
	0xd7, 0x32, 0xdd, 0x7d, 0xff, 0x6e, 0x79, 0xff, 0x34, 0x6e, 0x43, 0x0e, 0x47, 0x6f, 0x1b, 0x07,
	0xad, 0x37, 0x0e, 0xfa, 0xdc, 0x38, 0xe8, 0x39, 0x77, 0x4a, 0xeb, 0xdc, 0x29, 0x7d, 0xe4, 0x4e,
	0xe9, 0xa1, 0x17, 0x09, 0x98, 0x2d, 0xa7, 0x6e, 0xa0, 0x62, 0xcf, 0x0c, 0x85, 0x79, 0x66, 0x0b,
	0x2f, 0xdb, 0x5d, 0x7b, 0x95, 0x70, 0x3d, 0xad, 0x99, 0x3b, 0x5e, 0x7d, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0x24, 0xaf, 0xb8, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// AddERC20NativePointer defines a method to add a new ERC20 native pointer.
	AddERC20NativePointer(ctx context.Context, in *MsgAddERC20NativePointer, opts ...grpc.CallOption) (*MsgAddERC20NativePointerResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddERC20NativePointer(ctx context.Context, in *MsgAddERC20NativePointer, opts ...grpc.CallOption) (*MsgAddERC20NativePointerResponse, error) {
	out := new(MsgAddERC20NativePointerResponse)
	err := c.cc.Invoke(ctx, "/titan.pointer.Msg/AddERC20NativePointer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// AddERC20NativePointer defines a method to add a new ERC20 native pointer.
	AddERC20NativePointer(context.Context, *MsgAddERC20NativePointer) (*MsgAddERC20NativePointerResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddERC20NativePointer(ctx context.Context, req *MsgAddERC20NativePointer) (*MsgAddERC20NativePointerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddERC20NativePointer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddERC20NativePointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddERC20NativePointer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddERC20NativePointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.pointer.Msg/AddERC20NativePointer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddERC20NativePointer(ctx, req.(*MsgAddERC20NativePointer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "titan.pointer.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddERC20NativePointer",
			Handler:    _Msg_AddERC20NativePointer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "titan/pointer/tx.proto",
}

func (m *MsgAddERC20NativePointer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddERC20NativePointer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddERC20NativePointer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decimals != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddERC20NativePointerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddERC20NativePointerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddERC20NativePointerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddERC20NativePointer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovTx(uint64(m.Decimals))
	}
	return n
}

func (m *MsgAddERC20NativePointerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddERC20NativePointer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddERC20NativePointer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddERC20NativePointer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddERC20NativePointerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddERC20NativePointerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddERC20NativePointerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
