run:
  tests: true
  timeout: 5m
  concurrency: 4
  go: "1.22"

linters:
  enable:
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll TODO: enable
    - misspell
    - nakedret
    - prealloc
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - nolintlint
    - asciicheck
    - gofumpt
    - gomodguard   

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "var-naming:.*Id|var-naming:.*Uri|ST1003:.*Id|ST1003:.*Uri"
      linters:
        - stylecheck
        - revive    
    - text: "don't use an underscore in package name|ST1003:"
      linters:
        - revive
        - stylecheck
        


linters-settings:
  dogsled:
    max-blank-identifiers: 4
  golint:
    min-confidence: 0.8
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  gomodguard:
    blocked:
      versions:                                                         # List of blocked module version constraints
        - https://github.com/etcd-io/etcd:                              # Blocked module with version constraint
            version: ">= 3.4.10 || ~3.3.23"                             # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-15114; CVE-2020-15136; CVE-2020-15115"    # Reason why the version constraint exists. (Optional)
        - https://github.com/dgrijalva/jwt-go:                          # Blocked module with version constraint
            version: ">= 4.0.0-preview1"                                # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-26160"                                    # Reason why the version constraint exists. (Optional)
