version: 1

accounts:
- name: faucet
  coins: ['99994990tkx']
  # titan16e6pnctgxcnv8y9n27p285gdnmgyl6ndsuu2nr
  mnemonic: hair banner wedding drive age force situate shield tortoise coffee lucky rubber
- name: test
  # titan1up5lnguhgpu2qdqz9hav34yyvs0kjw3pruzrh7
  coins: ['1000tkx']
  mnemonic: throw beef member notable devote begin extend possible vibrant original point table
- name: test2
  # titan1ynme00xsfgugu4ucnumlxh30afzynqz95y0avt
  coins: ['1001tkx']
  mnemonic: vague actress result stage connect little skin fragile gift chef exile trophy
- name: val1
  # titan1cxjpv02d4cg7jp9qvh2her2lz5ljut0upv5gyv
  coins: ['1002tkx']
  mnemonic: tree text ghost clay fun asset audit focus carbon slab two aim
- name: val2
  # titan12gxum5krnqerwdtpc32ypvuwxlnnaq2kwxexl9
  coins: ['1003tkx']
  mnemonic: dignity include calm dinner frog clip bunker report grocery point actor home
- name: val3
  # titan1j90sphl02kuc5s465m9c33qpa28hrlx07qvjdp
  coins: ['1004tkx']
  mnemonic: merry strike spray access able edge rally bulk other butter involve situate

validators:
- name: val1
  bonded: 1000tkx
  home: "local_test_data/.titan_val1"
  app:
    minimum-gas-prices: 0atkx
    api.enable: true
    api.swagger: true
    api.enabled-unsafe-cors: true
  config:
    moniker: "titan val1"
    consensus: 
      create_empty_blocks: false
      create_empty_blocks_interval: 120s
      timeout_propose: 30s
      timeout_propose_delta: 5s
      timeout_prevote: 10s
      timeout_prevote_delta: 5s
      timeout_precommit: 10s
      timeout_precommit_delta: 5s
      timeout_commit: 5s
    rpc:
      timeout_broadcast_tx_commit: 20s
  client:
    chain-id: "titan_18888-1"
    keyring-backend: "test"

client:
  openapi:
    path: docs/static/openapi.yml

faucet:
  name: faucet
  coins: ['10tkx']

genesis:
  chain_id: titan_18888-1
  consensus_params:
    block:      
      max_gas: "20000000"
      time_iota_ms: "1000"
    evidence:
      max_age_num_blocks: "518400"
      max_age_duration: "2592000000000000"

  app_state:
    staking:
      params:
        bond_denom: "atkx"
        unbonding_time: "2592000s"
        max_validators: 188
    crisis:
      constant_fee:
        denom: "atkx"
        amount: "10000000000000000000"
    slashing:
      params:
        signed_blocks_window: "10000"
        min_signed_per_window: "0.050000000000000000"
        downtime_jail_duration: "600s"
        slash_fraction_double_sign: "0.050000000000000000"
        slash_fraction_downtime: "0.000100000000000000"
    gov:
      params:
        min_deposit:
        - denom: "atkx"
          amount: "250000000000000000000"  
        max_deposit_period: "604800s" 
        voting_period: "604800s"
    evm:
      params:
        evm_denom: "atkx"
    bank:
      denom_metadata:
      - name: "titan tkx"
        symbol: "TKX"
        display: "tkx"
        base: "atkx"
        description: "The native token of the Titan network."
        denom_units:
        - denom: "atkx"
          exponent: 0
          aliases:
          - "attotkx"
        - denom: "utkx"
          exponent: 12
          aliases:
          - "microtkx"
        - denom: "mtkx"
          exponent: 15
          aliases:
          - "millitkx"
        - denom: "tkx"
          exponent: 18

        
