version: 1

accounts:
- name: faucet
  coins: ['99994990tkx']
  # titan1xnpqgn3hz2xvg054w4cc5d5r9dh00nvj9cmkte
  mnemonic: object depart submit ritual civil culture garment rubber they laundry expose strike proud mushroom curious
- name: test
  # titan1k0v4rq689uq2s8yhttpmk0a26es8nrmqqkfh0p
  coins: ['1000tkx']
  mnemonic: envelope confirm theory tennis noodle monitor poet car lady rely salt latin border bounce knock
- name: test2
  # titan1ka0ycn78zm5zz326zf7aw3r7gpnwjwm8qn3agn
  coins: ['1001tkx']
  mnemonic: orient city dad visual junk accuse arch muscle tag fatal clump tube swarm unusual erosion
- name: val1
  # titan1rn4kdmg3qm6ga279kvlqa2n8mf4rheexq0ugt5
  coins: ['1002tkx']
  mnemonic: seek depth rigid improve wear able below whisper reward survey effort rescue unveil daring skate
- name: val2
  # titan1rsyy9ewhtzdj0v0jc6zj92j9dsmtll665ak0vc
  coins: ['1003tkx']
  mnemonic: health adapt wheel wheat caught inherit august dynamic ecology wheat ice magnet physical swap tower
- name: val3
  # titan1w6hnaps2tyr20pcp9gkt38m2srflsk7ctkmfee
  coins: ['1004tkx']
  mnemonic: federal gate food arrest three yard fence furnace cousin source toast expose perfect toward maid

validators:
- name: val1
  bonded: 1000tkx
  home: "local_test_data/.titan_val1"
  app:
    minimum-gas-prices: 0atkx
    api.enable: true
    api.swagger: true
    api.enabled-unsafe-cors: true
  config:
    moniker: "titan val1"
  client:
    chain-id: "titan_18888-1"
    keyring-backend: "test"

client:
  openapi:
    path: docs/static/openapi.yml

faucet:
  name: faucet
  coins: ['10tkx']

genesis:
  chain_id: titan_18888-1
  consensus_params:
    block:      
      max_gas: "2000000"

  app_state:
    staking:
      params:
        bond_denom: "atkx"
    crisis:
      constant_fee:
        denom: "tkx"
        amount: "1"
    gov:
      params:
        min_deposit:
        - denom: "tkx"
          amount: "1"   
    evm:
      params:
        evm_denom: "atkx"
