name: Discussion
description: Create a discussion
title: "[Discussion]: "
labels: ["T:discussion"]
body:
  - type: markdown
    attributes:
      value: |
       ✰  Thanks for opening an discussion! ✰  
  - type: textarea
    id: Detail
    attributes:
      label: Summary
      description: |
        What do you want to talk about?
      placeholder: Description of the proposed feature/changes/question to the repository
    validations:
      required: true  
