// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: titan/nftmint/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QuerySystemInfoRequest is request type for the Query/QuerySystemInfo RPC
// method.
type QuerySystemInfoRequest struct {
}

func (m *QuerySystemInfoRequest) Reset()         { *m = QuerySystemInfoRequest{} }
func (m *QuerySystemInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySystemInfoRequest) ProtoMessage()    {}
func (*QuerySystemInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{2}
}
func (m *QuerySystemInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySystemInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySystemInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySystemInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemInfoRequest.Merge(m, src)
}
func (m *QuerySystemInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySystemInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemInfoRequest proto.InternalMessageInfo

// QuerySystemInfoResponse is response type for the Query/QuerySystemInfo
// RPC method.
type QuerySystemInfoResponse struct {
	SystemInfo SystemInfo `protobuf:"bytes,1,opt,name=system_info,json=systemInfo,proto3" json:"system_info"`
}

func (m *QuerySystemInfoResponse) Reset()         { *m = QuerySystemInfoResponse{} }
func (m *QuerySystemInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySystemInfoResponse) ProtoMessage()    {}
func (*QuerySystemInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{3}
}
func (m *QuerySystemInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySystemInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySystemInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySystemInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemInfoResponse.Merge(m, src)
}
func (m *QuerySystemInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySystemInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemInfoResponse proto.InternalMessageInfo

func (m *QuerySystemInfoResponse) GetSystemInfo() SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return SystemInfo{}
}

// QueryMintingInfoRequest is request type for the Query/QueryMintingInfo RPC
// method.
type QueryMintingInfoRequest struct {
	ClassId string `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
}

func (m *QueryMintingInfoRequest) Reset()         { *m = QueryMintingInfoRequest{} }
func (m *QueryMintingInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMintingInfoRequest) ProtoMessage()    {}
func (*QueryMintingInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{4}
}
func (m *QueryMintingInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintingInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintingInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintingInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintingInfoRequest.Merge(m, src)
}
func (m *QueryMintingInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintingInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintingInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintingInfoRequest proto.InternalMessageInfo

func (m *QueryMintingInfoRequest) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

// QueryMintingInfoResponse is response type for the Query/QueryMintingInfo RPC
// method.
type QueryMintingInfoResponse struct {
	MintingInfo MintingInfo `protobuf:"bytes,1,opt,name=minting_info,json=mintingInfo,proto3" json:"minting_info"`
}

func (m *QueryMintingInfoResponse) Reset()         { *m = QueryMintingInfoResponse{} }
func (m *QueryMintingInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMintingInfoResponse) ProtoMessage()    {}
func (*QueryMintingInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{5}
}
func (m *QueryMintingInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintingInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintingInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintingInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintingInfoResponse.Merge(m, src)
}
func (m *QueryMintingInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintingInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintingInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintingInfoResponse proto.InternalMessageInfo

func (m *QueryMintingInfoResponse) GetMintingInfo() MintingInfo {
	if m != nil {
		return m.MintingInfo
	}
	return MintingInfo{}
}

// QueryMintingInfosRequest is request type for the Query/QueryMintingInfos RPC
// method.
type QueryMintingInfosRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMintingInfosRequest) Reset()         { *m = QueryMintingInfosRequest{} }
func (m *QueryMintingInfosRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMintingInfosRequest) ProtoMessage()    {}
func (*QueryMintingInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{6}
}
func (m *QueryMintingInfosRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintingInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintingInfosRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintingInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintingInfosRequest.Merge(m, src)
}
func (m *QueryMintingInfosRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintingInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintingInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintingInfosRequest proto.InternalMessageInfo

func (m *QueryMintingInfosRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryMintingInfosResponse is response type for the Query/QueryMintingInfos
// RPC method.
type QueryMintingInfosResponse struct {
	MintingInfo []MintingInfo       `protobuf:"bytes,1,rep,name=minting_info,json=mintingInfo,proto3" json:"minting_info"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMintingInfosResponse) Reset()         { *m = QueryMintingInfosResponse{} }
func (m *QueryMintingInfosResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMintingInfosResponse) ProtoMessage()    {}
func (*QueryMintingInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a41c9f8b8289cd, []int{7}
}
func (m *QueryMintingInfosResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintingInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintingInfosResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintingInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintingInfosResponse.Merge(m, src)
}
func (m *QueryMintingInfosResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintingInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintingInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintingInfosResponse proto.InternalMessageInfo

func (m *QueryMintingInfosResponse) GetMintingInfo() []MintingInfo {
	if m != nil {
		return m.MintingInfo
	}
	return nil
}

func (m *QueryMintingInfosResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "titan.nftmint.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "titan.nftmint.QueryParamsResponse")
	proto.RegisterType((*QuerySystemInfoRequest)(nil), "titan.nftmint.QuerySystemInfoRequest")
	proto.RegisterType((*QuerySystemInfoResponse)(nil), "titan.nftmint.QuerySystemInfoResponse")
	proto.RegisterType((*QueryMintingInfoRequest)(nil), "titan.nftmint.QueryMintingInfoRequest")
	proto.RegisterType((*QueryMintingInfoResponse)(nil), "titan.nftmint.QueryMintingInfoResponse")
	proto.RegisterType((*QueryMintingInfosRequest)(nil), "titan.nftmint.QueryMintingInfosRequest")
	proto.RegisterType((*QueryMintingInfosResponse)(nil), "titan.nftmint.QueryMintingInfosResponse")
}

func init() { proto.RegisterFile("titan/nftmint/query.proto", fileDescriptor_95a41c9f8b8289cd) }

var fileDescriptor_95a41c9f8b8289cd = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6e, 0x12, 0x41,
	0x18, 0xc7, 0xd9, 0x5a, 0x51, 0x3f, 0xea, 0x65, 0xac, 0x0a, 0x1b, 0xb3, 0xad, 0x1b, 0xa5, 0xb5,
	0xd6, 0x9d, 0x40, 0x35, 0x9e, 0x4c, 0x4c, 0x4d, 0x34, 0x98, 0x98, 0x54, 0xbc, 0xe9, 0x81, 0x0c,
	0x74, 0x58, 0x37, 0x76, 0x67, 0xb6, 0xcc, 0x60, 0x44, 0xd3, 0x8b, 0x0f, 0x60, 0x4c, 0x8c, 0x47,
	0x1f, 0xc0, 0x37, 0xe9, 0xcd, 0x26, 0x5e, 0x3c, 0x19, 0x03, 0x3e, 0x88, 0x61, 0x66, 0x80, 0x59,
	0x16, 0x41, 0x2f, 0x04, 0xe6, 0xfb, 0x7f, 0xdf, 0xff, 0x37, 0x33, 0xff, 0x01, 0x4a, 0x32, 0x92,
	0x84, 0x61, 0xd6, 0x96, 0x71, 0xc4, 0x24, 0x3e, 0xec, 0xd2, 0x4e, 0x2f, 0x48, 0x3a, 0x5c, 0x72,
	0x74, 0x5e, 0x95, 0x02, 0x53, 0x72, 0x57, 0x43, 0x1e, 0x72, 0x55, 0xc1, 0xc3, 0x6f, 0x5a, 0xe4,
	0x5e, 0x09, 0x39, 0x0f, 0x0f, 0x28, 0x26, 0x49, 0x84, 0x09, 0x63, 0x5c, 0x12, 0x19, 0x71, 0x26,
	0x4c, 0x75, 0xab, 0xc5, 0x45, 0xcc, 0x05, 0x6e, 0x12, 0x41, 0xf5, 0x6c, 0xfc, 0xba, 0xd2, 0xa4,
	0x92, 0x54, 0x70, 0x42, 0xc2, 0x88, 0x29, 0xb1, 0xd1, 0xba, 0x69, 0x92, 0x84, 0x74, 0x48, 0x3c,
	0x9a, 0xb3, 0x96, 0xae, 0x89, 0x9e, 0x90, 0x34, 0x6e, 0x44, 0xac, 0x3d, 0xc2, 0x58, 0x4f, 0x0b,
	0x86, 0x1f, 0x11, 0x0b, 0x2d, 0x85, 0xbf, 0x0a, 0xe8, 0xe9, 0x10, 0x60, 0x4f, 0xcd, 0xad, 0xd3,
	0xc3, 0x2e, 0x15, 0xd2, 0x7f, 0x0c, 0x17, 0x52, 0xab, 0x22, 0xe1, 0x4c, 0x50, 0xb4, 0x03, 0x79,
	0xed, 0x5f, 0x74, 0xd6, 0x9d, 0xcd, 0x42, 0xf5, 0x62, 0x90, 0x3a, 0x8b, 0x40, 0xcb, 0x77, 0x97,
	0x8f, 0x7f, 0xae, 0xe5, 0xea, 0x46, 0xea, 0x17, 0xe1, 0x92, 0x9a, 0xf5, 0x4c, 0xd1, 0xd5, 0x58,
	0x9b, 0x8f, 0x5c, 0x5e, 0xc0, 0xe5, 0x4c, 0xc5, 0x38, 0xdd, 0x87, 0x82, 0xb5, 0x1b, 0x63, 0x57,
	0x9a, 0xb2, 0x9b, 0xf4, 0x19, 0x4b, 0x10, 0xe3, 0x15, 0xff, 0xb6, 0x19, 0xfe, 0x44, 0xef, 0xd9,
	0xf2, 0x45, 0x25, 0x38, 0xdb, 0x3a, 0x20, 0x42, 0x34, 0xa2, 0x7d, 0x35, 0xf9, 0x5c, 0xfd, 0x8c,
	0xfa, 0x5d, 0xdb, 0xf7, 0x1b, 0x50, 0xcc, 0x76, 0x19, 0xa6, 0x07, 0xb0, 0x62, 0x1f, 0xa0, 0x81,
	0x72, 0xa7, 0xa0, 0xac, 0x4e, 0x43, 0x55, 0x88, 0x27, 0x4b, 0x7e, 0x33, 0x6b, 0x30, 0x3a, 0x75,
	0xf4, 0x10, 0x60, 0x72, 0xfd, 0x66, 0x7c, 0x39, 0xd0, 0x59, 0x09, 0x86, 0x59, 0x09, 0x74, 0x0e,
	0x4d, 0x56, 0x82, 0x3d, 0x12, 0x52, 0xd3, 0x5b, 0xb7, 0x3a, 0xfd, 0xaf, 0x0e, 0x94, 0x66, 0x98,
	0xfc, 0x75, 0x1b, 0xa7, 0xfe, 0x7b, 0x1b, 0xe8, 0x51, 0x0a, 0x75, 0x49, 0xa1, 0x6e, 0x2c, 0x44,
	0xd5, 0x04, 0x36, 0x6b, 0xf5, 0xdb, 0x32, 0x9c, 0x56, 0xac, 0xe8, 0x08, 0xf2, 0x3a, 0x3f, 0xe8,
	0xea, 0x14, 0x4b, 0x36, 0xa0, 0xae, 0x3f, 0x4f, 0xa2, 0x6d, 0xfc, 0xed, 0xf7, 0xdf, 0x7f, 0x7f,
	0x5a, 0x2a, 0xa3, 0x6b, 0x58, 0xf2, 0x57, 0x94, 0x45, 0x6f, 0xe9, 0x2d, 0xfd, 0x1c, 0x66, 0xbd,
	0x28, 0xf4, 0xc1, 0x01, 0x98, 0x04, 0x0a, 0x5d, 0x9f, 0x65, 0x90, 0x89, 0xb0, 0x5b, 0x5e, 0x24,
	0x33, 0x2c, 0x15, 0xc5, 0x72, 0x13, 0xdd, 0x98, 0xcf, 0x62, 0x65, 0x1e, 0x7d, 0x71, 0xa0, 0x60,
	0xdd, 0x02, 0x9a, 0x69, 0x95, 0x4d, 0xb7, 0xbb, 0xb1, 0x50, 0x67, 0x98, 0xee, 0x29, 0xa6, 0xbb,
	0xe8, 0xce, 0x7c, 0x26, 0x3b, 0x2c, 0xf8, 0xdd, 0xe8, 0xe1, 0x1c, 0xa1, 0xcf, 0x0e, 0xac, 0xd8,
	0x01, 0x43, 0x8b, 0x8c, 0xc7, 0x97, 0xb7, 0xb9, 0x58, 0x68, 0x10, 0xab, 0x0a, 0x71, 0x1b, 0x6d,
	0xfd, 0x3b, 0xe2, 0x6e, 0xed, 0xb8, 0xef, 0x39, 0x27, 0x7d, 0xcf, 0xf9, 0xd5, 0xf7, 0x9c, 0x8f,
	0x03, 0x2f, 0x77, 0x32, 0xf0, 0x72, 0x3f, 0x06, 0x5e, 0xee, 0x39, 0x0e, 0x23, 0xf9, 0xb2, 0xdb,
	0x0c, 0x5a, 0x3c, 0x9e, 0x3d, 0xef, 0xcd, 0x78, 0xa2, 0xec, 0x25, 0x54, 0x34, 0xf3, 0xea, 0x3f,
	0x72, 0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x2d, 0x3b, 0x98, 0x0e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// SystemInfo queries the system info of the module.
	SystemInfo(ctx context.Context, in *QuerySystemInfoRequest, opts ...grpc.CallOption) (*QuerySystemInfoResponse, error)
	// MintingInfo queries the minting info of a given class.
	MintingInfo(ctx context.Context, in *QueryMintingInfoRequest, opts ...grpc.CallOption) (*QueryMintingInfoResponse, error)
	// MintingInfos queries a list of minting info.
	MintingInfos(ctx context.Context, in *QueryMintingInfosRequest, opts ...grpc.CallOption) (*QueryMintingInfosResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/titan.nftmint.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SystemInfo(ctx context.Context, in *QuerySystemInfoRequest, opts ...grpc.CallOption) (*QuerySystemInfoResponse, error) {
	out := new(QuerySystemInfoResponse)
	err := c.cc.Invoke(ctx, "/titan.nftmint.Query/SystemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MintingInfo(ctx context.Context, in *QueryMintingInfoRequest, opts ...grpc.CallOption) (*QueryMintingInfoResponse, error) {
	out := new(QueryMintingInfoResponse)
	err := c.cc.Invoke(ctx, "/titan.nftmint.Query/MintingInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MintingInfos(ctx context.Context, in *QueryMintingInfosRequest, opts ...grpc.CallOption) (*QueryMintingInfosResponse, error) {
	out := new(QueryMintingInfosResponse)
	err := c.cc.Invoke(ctx, "/titan.nftmint.Query/MintingInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// SystemInfo queries the system info of the module.
	SystemInfo(context.Context, *QuerySystemInfoRequest) (*QuerySystemInfoResponse, error)
	// MintingInfo queries the minting info of a given class.
	MintingInfo(context.Context, *QueryMintingInfoRequest) (*QueryMintingInfoResponse, error)
	// MintingInfos queries a list of minting info.
	MintingInfos(context.Context, *QueryMintingInfosRequest) (*QueryMintingInfosResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SystemInfo(ctx context.Context, req *QuerySystemInfoRequest) (*QuerySystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemInfo not implemented")
}
func (*UnimplementedQueryServer) MintingInfo(ctx context.Context, req *QueryMintingInfoRequest) (*QueryMintingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintingInfo not implemented")
}
func (*UnimplementedQueryServer) MintingInfos(ctx context.Context, req *QueryMintingInfosRequest) (*QueryMintingInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintingInfos not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.nftmint.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.nftmint.Query/SystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SystemInfo(ctx, req.(*QuerySystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MintingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMintingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.nftmint.Query/MintingInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintingInfo(ctx, req.(*QueryMintingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MintingInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMintingInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintingInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.nftmint.Query/MintingInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintingInfos(ctx, req.(*QueryMintingInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "titan.nftmint.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SystemInfo",
			Handler:    _Query_SystemInfo_Handler,
		},
		{
			MethodName: "MintingInfo",
			Handler:    _Query_MintingInfo_Handler,
		},
		{
			MethodName: "MintingInfos",
			Handler:    _Query_MintingInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "titan/nftmint/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QuerySystemInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySystemInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySystemInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySystemInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySystemInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySystemInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SystemInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMintingInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintingInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintingInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMintingInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintingInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintingInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MintingInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMintingInfosRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintingInfosRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintingInfosRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMintingInfosResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintingInfosResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintingInfosResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MintingInfo) > 0 {
		for iNdEx := len(m.MintingInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintingInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QuerySystemInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySystemInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SystemInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMintingInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMintingInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MintingInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMintingInfosRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMintingInfosResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MintingInfo) > 0 {
		for _, e := range m.MintingInfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySystemInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySystemInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySystemInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySystemInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySystemInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySystemInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SystemInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintingInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintingInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintingInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintingInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintingInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintingInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintingInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintingInfosRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintingInfosRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintingInfosRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintingInfosResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintingInfosResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintingInfosResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintingInfo = append(m.MintingInfo, MintingInfo{})
			if err := m.MintingInfo[len(m.MintingInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
