name: Changelog Checks

on:
  pull_request:
    branches:
      - develop
      - release/**
      - main

jobs:
  updated:
    name: Check Changelog has updated
    runs-on: ubuntu-latest
    steps:
      - name: Check Changelog for changes
        uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
