name: Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Git fetch everything
        run: git fetch --prune --unshallow
      -
        name: Get Github tag
        id: meta
        run: |
          echo "tag=$(git describe --always --tags --match='v*')" >> "$GITHUB_OUTPUT"      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: titantkx
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: titantkx/titand:latest, titantkx/titand:${{ steps.meta.outputs.tag }}
